

@api = http://localhost:3005
@contentType = application/json

###

POST {{api}}/uploads
Content-Type: {{contentType}}

###

GET {{api}}/uploads
Content-Type: {{contentType}}

###

GET {{api}}/uploads/1
Content-Type: {{contentType}}

###